# Generated by Django 5.0.2 on 2024-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.jpg', null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
