# Generated by Django 5.0.2 on 2024-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0007_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='chatter.account'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='chatter.account'),
        ),
    ]
