# Generated by Django 5.0.2 on 2024-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0008_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to='chatter.account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='chatter.account'),
        ),
    ]
