# Generated by Django 5.0.2 on 2024-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Like'), (1, 'Comment'), (2, 'Follow')]),
        ),
    ]
