# Generated by Django 5.0.2 on 2024-03-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='notification_date',
        ),
    ]
