# Generated by Django 5.0.2 on 2024-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0014_notification_comment_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts'),
        ),
    ]
