# Generated by Django 5.0.2 on 2024-03-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0017_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
