# Generated by Django 5.0.2 on 2024-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0020_remove_notification_message_notification_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts'),
        ),
    ]
