# Generated by Django 5.0.2 on 2024-03-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0030_tag_remove_post_image_comment_tags_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='chatter.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='chatter.tag'),
        ),
    ]
